export enum ErrorCode {
  // Validation
  NO_FIELDS_TO_UPDATE = "NO_FIELDS_TO_UPDATE",
  CURRENT_PASSWORD_REQUIRED = "CURRENT_PASSWORD_REQUIRED",
  INVALID_EMAIL = "INVALID_EMAIL",
  MISSING_USER_DATA = "MISSING_USER_DATA",
  INVALID_DATE = "INVALID_DATE",

  // Authentication & Authorization
  USER_NOT_AUTHENTICATED = "USER_NOT_AUTHENTICATED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_CURRENT_PASSWORD = "INVALID_CURRENT_PASSWORD",
  FORBIDDEN_ACTION = "FORBIDDEN_ACTION",

  // User
  USER_NOT_FOUND = "USER_NOT_FOUND",
  EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE",
  EMAIL_ALREADY_USED = "EMAIL_ALREADY_USED",

  // Wallet
  WALLET_NOT_FOUND = "WALLET_NOT_FOUND",
  WALLET_ALREADY_EXISTS = "WALLET_ALREADY_EXISTS",
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
  INVALID_AMOUNT = "INVALID_AMOUNT",

  // Transaction
  TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND",
  TRANSACTION_CANNOT_BE_REVERSED = "TRANSACTION_CANNOT_BE_REVERSED",
  TRANSACTION_ALREADY_REVERSED = "TRANSACTION_ALREADY_REVERSED",
  INVALID_TRANSACTION_TYPE = "INVALID_TRANSACTION_TYPE",
  INVALID_TRANSACTION_STATUS = "INVALID_TRANSACTION_STATUS",
  RECEIVER_NOT_FOUND = "RECEIVER_NOT_FOUND",
  CANNOT_TRANSFER_TO_SELF = "CANNOT_TRANSFER_TO_SELF",
  INVALID_TOKEN = "INVALID_TOKEN",

  // Internal Server Errors
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
